replace all absolute imports with relative paths

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,21 +1,21 @@
 #!/usr/bin/env sh
-
+. "$(dirname "$0")/h"
 echo "Building project..."
 
 # Build the project
 # npm run build
 
 # Check if build was successful
-if [ $? -ne 0 ]; then
-  echo "Build failed! Commit aborted."
-  exit 1
-fi
+# if [ $? -ne 0 ]; then
+#   echo "Build failed! Commit aborted."
+#   exit 1
+# fi
 
-echo "Build successful!"
+# echo "Build successful!"
 
-# Add dist folder to staging area
-git add dist/
+# # Add dist folder to staging area
+# git add dist/
 
-echo "Added dist/ to commit"
+# echo "Added dist/ to commit"
 
-echo "Pre-commit checks passed!"
+# echo "Pre-commit checks passed!"
